name: sloppymodern
channels:
  - conda-forge
  - defaults
dependencies:
  - datashader=0.17.*
  - hvplot=1.20.*
  - ipykernel
  - ipympl
  - ipywidgets
  - k3d=2.16.*
  - matplotlib
  - numba
  - numpy
  - python=3.10
